services:
  algo_analytics:
    image: algo_analytics:v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: algo_analytics
    restart: "no"
    ports:
      - "8888:8888" 
    volumes:
      - ./VN30F1M:/analytics/VN30F1M
      - ./Downloads:/analytics/Downloads
    networks:
      - algo_net

networks:
  algo_net:
